### ISSUE TITLE
Sample commands are not working

### ISSUE THREAD

**Issue by fikretalim** [rushad7/mask-detection#1]
Hello,

I got errors both running live video and image samples. What can be the problem?

python yolo-live-cv2.py --yolo yolo
[INFO] loading YOLO from disk
Traceback (most recent call last):
  File "yolo-live-cv2.py", line 32, in <module>
    net = cv2.dnn.readNetFromDarknet(configPath, weightsPath)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:712: error: (-213:The function/feature is not implemented) Transpose the weights (except for convolutional) is not implemented in function 'ReadDarknetFromWeightsStream'

python custom_detector.py --image /home/fikret/project/yolov3_projects/face-mask-detector/dataset/with_mask/0-with-mask.jpg --config cfg/yolov3-custom.cfg --weights weights/yolov3-custom_final.weights --names class_names/custom.names 
Traceback (most recent call last):
  File "custom_detector.py", line 18, in <module>
    net = cv2.dnn.readNetFromDarknet(args.config, args.weights)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:712: error: (-213:The function/feature is not implemented) Transpose the weights (except for convolutional) is not implemented in function 'ReadDarknetFromWeightsStream'

**Comment by rushad7** [comment]
It looks like the .weights file is missing from the weights and yolo folder. This is because the bandwidth has been exceeded on Git LFS
