### ISSUE TITLE
weights file does not seem to contain the weights

### ISSUE THREAD

**Issue by peace-to-all** [rushad7/mask-detection#2]
The weights file does not seem to contain the pre-trained weights. I think there may be some git large file error. The yolov3-custom_final.weights file just contains the following 3 lines

version https://git-lfs.github.com/spec/v1
oid sha256:294e8acd929267bf458019d6aee18559d9605c1f7081e8ddbca99cba37897f93
size 246326928

**Comment by rushad7** [comment]
Yes, this is happening because I used Git LFS, and have run out of the free monthly bandwidth. I will soon make the weights available
