### ISSUE TITLE
config file does not even reflect the problem!!

### ISSUE THREAD

**Issue by Maziar-Kasaei** [rushad7/mask-detection#4]
I opened your config file and it does not show 2 classes. it shows 80 classes. And you say directly use this to test however, your config file is in the training mode. Plus, the custom weights file is not even a weights file.

**Comment by rushad7** [comment]
Thanks for pointing out the issue! I realized that I pushed the default darknet config file instead of the custom file. I have made the respective changes. The weights will be available shortly.
